version: "3"

services:
  backend:
    build: ./backend
    volumes:
      - ./backend/:/backend
    working_dir: /backend/
    command: sh docker-compose-entrypoint.sh
  frontend:
    image: node:10
    volumes:
      - ./frontend/:/frontend
    working_dir: /frontend
    command: sh docker-compose-entrypoint.sh
  nginx:
    image: nginx:latest
    ports:
      - 80:5000
    volumes:
      - ./nginx/nginx-proxy.conf:/etc/nginx/conf.d/default.conf:ro
      - ./frontend/build:/var/www/frontend
    depends_on:
      - backend
